/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clearallblock;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTextField;


/**
 *
 * @author prabin
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    int gridSize;
    JTextField[][] txtField;
    int maxColor;
    ArrayList<String> levels;

    public Board(int gridSize, int maxColor) {
        initComponents();

        this.maxColor = maxColor;
        this.gridSize = gridSize;

        System.out.println(gridSize + " " + maxColor);

        drawringPanel.setLayout(new GridLayout(gridSize, gridSize));
        lblTitle.setText("Grid Size:" + gridSize + "x" + gridSize + "-:- " + "Set of balls: " + maxColor);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        addTextBox();
        hint = "";
        levels = new ArrayList<String>();
        readCurrentlevel();
        lblLevel.setText("current level: " + levels.size());
    }
    
    public void readCurrentlevel(){
    
        try{
            BufferedReader read = new BufferedReader(new FileReader("d:\\moveit levelfile\\" + this.gridSize +"_"+this.maxColor +".txt"));
            
            String str;
            while ((str =read.readLine())!= null) {
               
                levels.add(str);
                
            }
   
            read.close();
        } catch(IOException e){
        
        }
    }
    JTextField txtRef;

    public void setObject(MouseEvent event) {

        txtRef = (JTextField) event.getComponent();

        new SelectOption(this, maxColor);
    }

    public void addTextBox() {

        txtField = new JTextField[gridSize][gridSize];

        for (int i = 0; i < gridSize; i++) {

            for (int j = 0; j < gridSize; j++) {

                txtField[i][j] = new JTextField("00");
                txtField[i][j].setSize(300, 300);
                txtField[i][j].setForeground(Color.GRAY);


                txtField[i][j].setBackground(Color.lightGray);
                txtField[i][j].setFont(new java.awt.Font("Times New Roman", 0, 14));

                txtField[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        setObject(evt);
                    }
                });

                drawringPanel.add(txtField[i][j]);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawringPanel = new java.awt.Panel();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnHints = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawringPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout drawringPanelLayout = new javax.swing.GroupLayout(drawringPanel);
        drawringPanel.setLayout(drawringPanelLayout);
        drawringPanelLayout.setHorizontalGroup(
            drawringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        drawringPanelLayout.setVerticalGroup(
            drawringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        btnBack.setText("back to main");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setText("reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(255, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("jLabel1");
        lblTitle.setPreferredSize(new java.awt.Dimension(50, 50));

        btnHints.setText("set hints");
        btnHints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintsActionPerformed(evt);
            }
        });

        lblMsg.setText("Message");

        lblLevel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drawringPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(btnHints, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMsg)
                            .addComponent(lblLevel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblLevel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnHints, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(drawringPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblMsg)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        new MainWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < gridSize; i++) {

            for (int j = 0; j < gridSize; j++) {

                txtField[i][j].setText("00");
            }


        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BufferedWriter out;
        try {
            String str = "";
            for (int i = 0; i < gridSize; i++) {

                for (int j = 0; j < gridSize; j++) {

                    if(j < gridSize - 1){
                        str += txtField[i][j].getText() + ",";
                    } else {
                        str += txtField[i][j].getText() + ";";
                    }
                    
                }
            }
            str += hint;
            
            for(String level : levels){
                if(level.equals(str)){
                    lblMsg.setText("File already exists, make another one");
                    return;
                }
                
            }
            
            levels.add(str);
            lblLevel.setText("current level: " + levels.size());
         
            str +="\n";
            File file = new File("d:\\moveit levelfile");
            if(!file.exists()){
                file.mkdir();
            }
            out = new BufferedWriter(new FileWriter(file + "\\" + this.gridSize +"_"+this.maxColor +".txt", true));
           
            out.append(str);
            
            out.close();
            lblMsg.setText("file generated  "+ str);
        } catch (IOException ex) {
          lblMsg.setText("failed"+ ex);
        } 
        
    }//GEN-LAST:event_jButton2ActionPerformed

  String hint;
    private void btnHintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintsActionPerformed
        // TODO add your handling code here:
        new Hint(this);
        
       
    }//GEN-LAST:event_btnHintsActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHints;
    private java.awt.Panel drawringPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
