/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clearallblock;

/**
 *
 * @author prabin
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGridSize = new javax.swing.JLabel();
        comboGridSize = new javax.swing.JComboBox();
        lblNoOfBallls = new javax.swing.JLabel();
        comboNoOfBalls = new javax.swing.JComboBox();
        btnNextMainWin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGridSize.setText("Select Grid Size");

        comboGridSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x3", "4x4", "5x5" }));
        comboGridSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGridSizeActionPerformed(evt);
            }
        });

        lblNoOfBallls.setText("Select no different balls");

        comboNoOfBalls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        comboNoOfBalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNoOfBallsActionPerformed(evt);
            }
        });

        btnNextMainWin.setText("Next");
        btnNextMainWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMainWinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNextMainWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGridSize)
                            .addComponent(lblNoOfBallls))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboGridSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboNoOfBalls, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGridSize)
                    .addComponent(comboGridSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoOfBallls)
                    .addComponent(comboNoOfBalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnNextMainWin)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextMainWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextMainWinActionPerformed

        String grid = comboGridSize.getSelectedItem().toString();



        new Board(grid.charAt(0) - 48, Integer.parseInt(comboNoOfBalls.getSelectedItem().toString()));

        this.dispose();
    }//GEN-LAST:event_btnNextMainWinActionPerformed

    private void comboNoOfBallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNoOfBallsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNoOfBallsActionPerformed

    private void comboGridSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGridSizeActionPerformed
        int selectedIndex = comboGridSize.getSelectedIndex();
        switch (selectedIndex) {

            case 0:
                comboNoOfBalls.removeAllItems();
                for (int i = 1; i <= 3; i++) {
                    comboNoOfBalls.addItem(i);
                }
                break;

            case 1:
                comboNoOfBalls.removeAllItems();
                for (int i = 1; i <= 4; i++) {
                    comboNoOfBalls.addItem(i);
                }
                break;

            case 2:
                comboNoOfBalls.removeAllItems();
                for (int i = 1; i <= 5; i++) {
                    comboNoOfBalls.addItem(i);
                }
                break;
        }
    }//GEN-LAST:event_comboGridSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextMainWin;
    private javax.swing.JComboBox comboGridSize;
    private javax.swing.JComboBox comboNoOfBalls;
    private javax.swing.JLabel lblGridSize;
    private javax.swing.JLabel lblNoOfBallls;
    // End of variables declaration//GEN-END:variables
}
