package clearallblock;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author prabin
 */
public class SelectOption extends javax.swing.JFrame {

    int maxColors;
    JButton[] btnColors;
    JButton btnBlock;
    Board board;

    public SelectOption(Board board, int maxColors) {
        initComponents();

        this.board = board;
        this.maxColors = maxColors;

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        activateValidButtons();

    }

    public void activateValidButtons() {

        switch (maxColors) {

            case 1:

                btnBallRed.setEnabled(false);
                btnBallGreen.setEnabled(false);
                btnBallYellow.setEnabled(false);
                btnBallOrange.setEnabled(false);
                
                btnGridRed.setEnabled(false);
                btnGridGreen.setEnabled(false);
                btnGridYellow.setEnabled(false);
                btnGridOrange.setEnabled(false);

                break;

            case 2:
                btnBallRed.setEnabled(true);
                btnBallGreen.setEnabled(false);
                btnBallYellow.setEnabled(false);
                btnBallOrange.setEnabled(false);
                
                btnGridRed.setEnabled(true);
                btnGridGreen.setEnabled(false);
                btnGridYellow.setEnabled(false);
                btnGridOrange.setEnabled(false);

                break;

            case 3:

                btnBallRed.setEnabled(true);
                btnBallGreen.setEnabled(true);
                btnBallYellow.setEnabled(false);
                btnBallOrange.setEnabled(false);
                
                btnGridRed.setEnabled(true);
                btnGridGreen.setEnabled(true);
                btnGridYellow.setEnabled(false);
                btnGridOrange.setEnabled(false);

                break;

            case 4:
                btnBallRed.setEnabled(true);
                btnBallGreen.setEnabled(true);
                btnBallYellow.setEnabled(true);
                btnBallOrange.setEnabled(false);
                
                btnGridRed.setEnabled(true);
                btnGridGreen.setEnabled(true);
                btnGridYellow.setEnabled(true);
                btnGridOrange.setEnabled(false);

                break;
            case 5:

                btnBallRed.setEnabled(true);
                btnBallGreen.setEnabled(true);
                btnBallYellow.setEnabled(true);
                btnBallOrange.setEnabled(true);
                
                 btnGridRed.setEnabled(true);
                btnGridGreen.setEnabled(true);
                btnGridYellow.setEnabled(true);
                btnGridOrange.setEnabled(true);

                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBallBlue = new javax.swing.JButton();
        btnBallRed = new javax.swing.JButton();
        btnBallGreen = new javax.swing.JButton();
        btnBallYellow = new javax.swing.JButton();
        btnBallOrange = new javax.swing.JButton();
        lblBallColor = new javax.swing.JLabel();
        lblBlock = new javax.swing.JLabel();
        bntSetBlock = new javax.swing.JButton();
        lblSetGridColor = new javax.swing.JLabel();
        btnGridBlue = new javax.swing.JButton();
        btnGridOrange = new javax.swing.JButton();
        btnGridRed = new javax.swing.JButton();
        btnGridGreen = new javax.swing.JButton();
        btnGridYellow = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBallBlue.setBackground(new java.awt.Color(204, 204, 204));
        btnBallBlue.setForeground(new java.awt.Color(51, 153, 255));
        btnBallBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circles/blue.png"))); // NOI18N
        btnBallBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallBlueActionPerformed(evt);
            }
        });

        btnBallRed.setBackground(new java.awt.Color(204, 204, 204));
        btnBallRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circles/red.png"))); // NOI18N
        btnBallRed.setEnabled(false);
        btnBallRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallRedActionPerformed(evt);
            }
        });

        btnBallGreen.setBackground(new java.awt.Color(204, 204, 204));
        btnBallGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circles/green.png"))); // NOI18N
        btnBallGreen.setEnabled(false);
        btnBallGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallGreenActionPerformed(evt);
            }
        });

        btnBallYellow.setBackground(new java.awt.Color(204, 204, 204));
        btnBallYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circles/yellow.png"))); // NOI18N
        btnBallYellow.setEnabled(false);
        btnBallYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallYellowActionPerformed(evt);
            }
        });

        btnBallOrange.setBackground(new java.awt.Color(204, 204, 204));
        btnBallOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circles/orange.png"))); // NOI18N
        btnBallOrange.setEnabled(false);
        btnBallOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallOrangeActionPerformed(evt);
            }
        });

        lblBallColor.setText("BAll color selector");

        lblBlock.setText("Block");

        bntSetBlock.setBackground(new java.awt.Color(153, 153, 153));
        bntSetBlock.setText("Set Block");
        bntSetBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSetBlockActionPerformed(evt);
            }
        });

        lblSetGridColor.setText("Grid Color Chooser");

        btnGridBlue.setBackground(new java.awt.Color(153, 255, 255));
        btnGridBlue.setText("Blue");
        btnGridBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridBlueActionPerformed(evt);
            }
        });

        btnGridOrange.setBackground(new java.awt.Color(255, 204, 0));
        btnGridOrange.setText("Orange");
        btnGridOrange.setEnabled(false);
        btnGridOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridOrangeActionPerformed(evt);
            }
        });

        btnGridRed.setBackground(new java.awt.Color(255, 102, 102));
        btnGridRed.setText("Red");
        btnGridRed.setEnabled(false);
        btnGridRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridRedActionPerformed(evt);
            }
        });

        btnGridGreen.setBackground(new java.awt.Color(102, 255, 102));
        btnGridGreen.setText("Green");
        btnGridGreen.setEnabled(false);
        btnGridGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridGreenActionPerformed(evt);
            }
        });

        btnGridYellow.setBackground(new java.awt.Color(255, 255, 153));
        btnGridYellow.setText("Yellow");
        btnGridYellow.setEnabled(false);
        btnGridYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridYellowActionPerformed(evt);
            }
        });

        btnClear.setText("clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBallColor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlock)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBallBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnBallRed, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBallGreen)
                                .addGap(18, 18, 18)
                                .addComponent(btnBallYellow)
                                .addGap(18, 18, 18)
                                .addComponent(btnBallOrange))
                            .addComponent(lblSetGridColor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntSetBlock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnGridBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnGridRed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnGridGreen)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGridYellow)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGridOrange))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)))))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBallColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBallBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBallOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBallRed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBallGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBallYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblBlock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(bntSetBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblSetGridColor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGridBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnGridOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGridRed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGridGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGridYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBallGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallGreenActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(0, '3');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnBallGreenActionPerformed

    private void btnBallYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallYellowActionPerformed

        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(0, '4');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnBallYellowActionPerformed

    private void btnBallOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallOrangeActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(0, '5');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnBallOrangeActionPerformed

    private void btnGridOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridOrangeActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(1, '5');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnGridOrangeActionPerformed

    private void btnGridGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridGreenActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(1, '3');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnGridGreenActionPerformed

    private void btnGridYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridYellowActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(1, '4');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnGridYellowActionPerformed

    private void btnBallBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallBlueActionPerformed

        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(0, '1');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnBallBlueActionPerformed

    private void btnBallRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallRedActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(0, '2');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnBallRedActionPerformed

    private void bntSetBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSetBlockActionPerformed
        
        board.txtRef.setText("-1");
        this.dispose();
    }//GEN-LAST:event_bntSetBlockActionPerformed

    private void btnGridBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridBlueActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(1, '1');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnGridBlueActionPerformed

    private void btnGridRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridRedActionPerformed
        StringBuilder strBldr = new StringBuilder(board.txtRef.getText().toString());
        strBldr.setCharAt(1, '2');
        board.txtRef.setText(strBldr.toString());
        this.dispose();
    }//GEN-LAST:event_btnGridRedActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       
        
        board.txtRef.setText("00");
        this.dispose();
    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSetBlock;
    private javax.swing.JButton btnBallBlue;
    private javax.swing.JButton btnBallGreen;
    private javax.swing.JButton btnBallOrange;
    private javax.swing.JButton btnBallRed;
    private javax.swing.JButton btnBallYellow;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGridBlue;
    private javax.swing.JButton btnGridGreen;
    private javax.swing.JButton btnGridOrange;
    private javax.swing.JButton btnGridRed;
    private javax.swing.JButton btnGridYellow;
    private javax.swing.JLabel lblBallColor;
    private javax.swing.JLabel lblBlock;
    private javax.swing.JLabel lblSetGridColor;
    // End of variables declaration//GEN-END:variables
}
